// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_state.sql

package sqlc

import (
	"context"
)

const getActiveYear = `-- name: GetActiveYear :one
SELECT active_year FROM app_state WHERE id = 1
`

func (q *Queries) GetActiveYear(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveYear)
	var active_year int64
	err := row.Scan(&active_year)
	return active_year, err
}

const setActiveYear = `-- name: SetActiveYear :exec
INSERT INTO app_state (id, active_year) VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET active_year = excluded.active_year
`

func (q *Queries) SetActiveYear(ctx context.Context, activeYear int64) error {
	_, err := q.db.ExecContext(ctx, setActiveYear, activeYear)
	return err
}
