// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_event (actor_id, actor_email, kind, entity_type, entity_id, timestamp, payload)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditEventParams struct {
	ActorID    sql.NullInt64
	ActorEmail string
	Kind       string
	EntityType string
	EntityID   string
	Timestamp  string
	Payload    sql.NullString
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEvent,
		arg.ActorID,
		arg.ActorEmail,
		arg.Kind,
		arg.EntityType,
		arg.EntityID,
		arg.Timestamp,
		arg.Payload,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor_id, actor_email, kind, entity_type, entity_id, timestamp, payload
FROM audit_event ORDER BY id
`

func (q *Queries) ListAuditEvents(ctx context.Context) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorEmail,
			&i.Kind,
			&i.EntityType,
			&i.EntityID,
			&i.Timestamp,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
