// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board.sql

package sqlc

import (
	"context"
	"database/sql"
)

const listBoardAuthorizationsByPartner = `-- name: ListBoardAuthorizationsByPartner :many
SELECT partner_id, scope_kind, section_code
FROM board_authorization WHERE partner_id = ? ORDER BY scope_kind, section_code
`

func (q *Queries) ListBoardAuthorizationsByPartner(ctx context.Context, partnerID int64) ([]BoardAuthorization, error) {
	rows, err := q.db.QueryContext(ctx, listBoardAuthorizationsByPartner, partnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardAuthorization{}
	for rows.Next() {
		var i BoardAuthorization
		if err := rows.Scan(&i.PartnerID, &i.ScopeKind, &i.SectionCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBoardAuthorization = `-- name: UpsertBoardAuthorization :exec
INSERT INTO board_authorization (partner_id, scope_kind, section_code)
VALUES (?, ?, ?)
ON CONFLICT(partner_id, scope_kind, COALESCE(section_code, '')) DO NOTHING
`

type UpsertBoardAuthorizationParams struct {
	PartnerID   int64
	ScopeKind   string
	SectionCode sql.NullString
}

func (q *Queries) UpsertBoardAuthorization(ctx context.Context, arg UpsertBoardAuthorizationParams) error {
	_, err := q.db.ExecContext(ctx, upsertBoardAuthorization, arg.PartnerID, arg.ScopeKind, arg.SectionCode)
	return err
}
