// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forecast.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteForecast = `-- name: DeleteForecast :exec
DELETE FROM expense_forecast WHERE id = ?
`

func (q *Queries) DeleteForecast(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteForecast, id)
	return err
}

const getForecast = `-- name: GetForecast :one
SELECT id, partner_id, concept, description, gross_amount, approved_amount, approved_on,
       planned_date, year, subtype_code, scope_kind, section_code, added_on, enabled
FROM expense_forecast WHERE id = ?
`

func (q *Queries) GetForecast(ctx context.Context, id string) (ExpenseForecast, error) {
	row := q.db.QueryRowContext(ctx, getForecast, id)
	var i ExpenseForecast
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.Concept,
		&i.Description,
		&i.GrossAmount,
		&i.ApprovedAmount,
		&i.ApprovedOn,
		&i.PlannedDate,
		&i.Year,
		&i.SubtypeCode,
		&i.ScopeKind,
		&i.SectionCode,
		&i.AddedOn,
		&i.Enabled,
	)
	return i, err
}

const insertForecast = `-- name: InsertForecast :exec
INSERT INTO expense_forecast
  (id, partner_id, concept, description, gross_amount, approved_amount, approved_on,
   planned_date, year, subtype_code, scope_kind, section_code, added_on, enabled)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertForecastParams struct {
	ID             string
	PartnerID      int64
	Concept        string
	Description    string
	GrossAmount    string
	ApprovedAmount string
	ApprovedOn     sql.NullString
	PlannedDate    string
	Year           int64
	SubtypeCode    string
	ScopeKind      string
	SectionCode    sql.NullString
	AddedOn        string
	Enabled        int64
}

func (q *Queries) InsertForecast(ctx context.Context, arg InsertForecastParams) error {
	_, err := q.db.ExecContext(ctx, insertForecast,
		arg.ID,
		arg.PartnerID,
		arg.Concept,
		arg.Description,
		arg.GrossAmount,
		arg.ApprovedAmount,
		arg.ApprovedOn,
		arg.PlannedDate,
		arg.Year,
		arg.SubtypeCode,
		arg.ScopeKind,
		arg.SectionCode,
		arg.AddedOn,
		arg.Enabled,
	)
	return err
}

const listForecastIDsByYear = `-- name: ListForecastIDsByYear :many
SELECT id FROM expense_forecast WHERE year = ?
`

func (q *Queries) ListForecastIDsByYear(ctx context.Context, year int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listForecastIDsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForecastsByYear = `-- name: ListForecastsByYear :many
SELECT id, partner_id, concept, description, gross_amount, approved_amount, approved_on,
       planned_date, year, subtype_code, scope_kind, section_code, added_on, enabled
FROM expense_forecast WHERE year = ? ORDER BY id
`

func (q *Queries) ListForecastsByYear(ctx context.Context, year int64) ([]ExpenseForecast, error) {
	rows, err := q.db.QueryContext(ctx, listForecastsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseForecast{}
	for rows.Next() {
		var i ExpenseForecast
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.Concept,
			&i.Description,
			&i.GrossAmount,
			&i.ApprovedAmount,
			&i.ApprovedOn,
			&i.PlannedDate,
			&i.Year,
			&i.SubtypeCode,
			&i.ScopeKind,
			&i.SectionCode,
			&i.AddedOn,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForecast = `-- name: UpdateForecast :exec
UPDATE expense_forecast SET
  partner_id=?, concept=?, description=?, gross_amount=?, approved_amount=?, approved_on=?,
  planned_date=?, year=?, subtype_code=?, scope_kind=?, section_code=?, added_on=?, enabled=?
WHERE id=?
`

type UpdateForecastParams struct {
	PartnerID      int64
	Concept        string
	Description    string
	GrossAmount    string
	ApprovedAmount string
	ApprovedOn     sql.NullString
	PlannedDate    string
	Year           int64
	SubtypeCode    string
	ScopeKind      string
	SectionCode    sql.NullString
	AddedOn        string
	Enabled        int64
	ID             string
}

func (q *Queries) UpdateForecast(ctx context.Context, arg UpdateForecastParams) error {
	_, err := q.db.ExecContext(ctx, updateForecast,
		arg.PartnerID,
		arg.Concept,
		arg.Description,
		arg.GrossAmount,
		arg.ApprovedAmount,
		arg.ApprovedOn,
		arg.PlannedDate,
		arg.Year,
		arg.SubtypeCode,
		arg.ScopeKind,
		arg.SectionCode,
		arg.AddedOn,
		arg.Enabled,
		arg.ID,
	)
	return err
}
