// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type AuditEvent struct {
	ID         int64
	ActorID    sql.NullInt64
	ActorEmail string
	Kind       string
	EntityType string
	EntityID   string
	Timestamp  string
	Payload    sql.NullString
}

type BoardAuthorization struct {
	PartnerID   int64
	ScopeKind   string
	SectionCode sql.NullString
}

type Concession struct {
	Year           int64
	GroupCode      string
	SubtypeCode    string
	Concept        string
	RequestedTotal string
	GrantedAmount  string
}

type ConcessionForecast struct {
	Year       int64
	ForecastID string
	GroupCode  string
}

type ExpenseForecast struct {
	ID             string
	PartnerID      int64
	Concept        string
	Description    string
	GrossAmount    string
	ApprovedAmount string
	ApprovedOn     sql.NullString
	PlannedDate    string
	Year           int64
	SubtypeCode    string
	ScopeKind      string
	SectionCode    sql.NullString
	AddedOn        string
	Enabled        int64
}

type ExpenseSubtype struct {
	Year     int64
	Code     string
	Label    string
	TypeCode string
}

type ExpenseType struct {
	Year     int64
	Code     string
	Label    string
	Category string
}

type ForecastInvoice struct {
	ForecastID string
	InvoiceID  int64
	Amount     string
}

type Invoice struct {
	ID        int64
	Year      int64
	Issuer    string
	Nif       string
	Number    string
	IssueDate string
	NetAmount string
	FilePath  sql.NullString
	Notes     sql.NullString
}

type InvoicePayment struct {
	ID        int64
	InvoiceID int64
	PaidOn    string
	Amount    string
}

type Partner struct {
	ID          int64
	Name        string
	Surname     string
	VatCode     string
	Email       string
	Mobile      string
	PartnerType string
	RiaNumber   int64
	AddedOn     string
	BoardMember int64
	NickName    string
}

type PartnerSection struct {
	PartnerID   int64
	SectionCode string
}

type ReconciliationSnapshot struct {
	Year         int64
	GeneratedAt  string
	SnapshotJson string
	Pdf          []byte
}

type Report struct {
	ID           int64
	Year         int64
	GeneratedAt  string
	SnapshotJson string
	Pdf          []byte
	SupersededAt sql.NullString
}

type Section struct {
	Code         string
	Label        string
	Active       int64
	DisplayOrder int64
}

type Session struct {
	Token     string
	PartnerID int64
	Email     string
	CreatedAt string
	ExpiresAt string
}

type SubmissionWindow struct {
	Year                   int64
	State                  string
	OpenedAt               sql.NullString
	ClosedAt               sql.NullString
	Deadline               string
	CurrentExpenseLimit    string
	InvestmentExpenseLimit string
}
