// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: partner.sql

package sqlc

import (
	"context"
)

const getPartner = `-- name: GetPartner :one
SELECT id, name, surname, vat_code, email, mobile, partner_type, ria_number, added_on, board_member
FROM partner WHERE id = ?
`

func (q *Queries) GetPartner(ctx context.Context, id int64) (Partner, error) {
	row := q.db.QueryRowContext(ctx, getPartner, id)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.VatCode,
		&i.Email,
		&i.Mobile,
		&i.PartnerType,
		&i.RiaNumber,
		&i.AddedOn,
		&i.BoardMember,
	)
	return i, err
}

const getPartnerByEmail = `-- name: GetPartnerByEmail :one
SELECT id, name, surname, vat_code, email, mobile, partner_type, ria_number, added_on, board_member
FROM partner WHERE email = ?
`

func (q *Queries) GetPartnerByEmail(ctx context.Context, email string) (Partner, error) {
	row := q.db.QueryRowContext(ctx, getPartnerByEmail, email)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.VatCode,
		&i.Email,
		&i.Mobile,
		&i.PartnerType,
		&i.RiaNumber,
		&i.AddedOn,
		&i.BoardMember,
	)
	return i, err
}

const listPartners = `-- name: ListPartners :many
SELECT id, name, surname, vat_code, email, mobile, partner_type, ria_number, added_on, board_member
FROM partner ORDER BY id
`

func (q *Queries) ListPartners(ctx context.Context) ([]Partner, error) {
	rows, err := q.db.QueryContext(ctx, listPartners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Partner{}
	for rows.Next() {
		var i Partner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.VatCode,
			&i.Email,
			&i.Mobile,
			&i.PartnerType,
			&i.RiaNumber,
			&i.AddedOn,
			&i.BoardMember,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPartner = `-- name: UpsertPartner :exec
INSERT INTO partner (id, name, surname, vat_code, email, mobile, partner_type, ria_number, added_on, board_member)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  name=excluded.name, surname=excluded.surname, vat_code=excluded.vat_code,
  email=excluded.email, mobile=excluded.mobile, partner_type=excluded.partner_type,
  ria_number=excluded.ria_number, added_on=excluded.added_on, board_member=excluded.board_member
`

type UpsertPartnerParams struct {
	ID          int64
	Name        string
	Surname     string
	VatCode     string
	Email       string
	Mobile      string
	PartnerType string
	RiaNumber   int64
	AddedOn     string
	BoardMember int64
}

func (q *Queries) UpsertPartner(ctx context.Context, arg UpsertPartnerParams) error {
	_, err := q.db.ExecContext(ctx, upsertPartner,
		arg.ID,
		arg.Name,
		arg.Surname,
		arg.VatCode,
		arg.Email,
		arg.Mobile,
		arg.PartnerType,
		arg.RiaNumber,
		arg.AddedOn,
		arg.BoardMember,
	)
	return err
}
