// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation_snapshot.sql

package sqlc

import (
	"context"
)

const getReconciliationSnapshotByYear = `-- name: GetReconciliationSnapshotByYear :one
SELECT year, generated_at, snapshot_json, pdf
FROM reconciliation_snapshot
WHERE year = ?
`

func (q *Queries) GetReconciliationSnapshotByYear(ctx context.Context, year int64) (ReconciliationSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getReconciliationSnapshotByYear, year)
	var i ReconciliationSnapshot
	err := row.Scan(
		&i.Year,
		&i.GeneratedAt,
		&i.SnapshotJson,
		&i.Pdf,
	)
	return i, err
}

const upsertReconciliationSnapshot = `-- name: UpsertReconciliationSnapshot :exec
INSERT INTO reconciliation_snapshot (year, generated_at, snapshot_json, pdf)
VALUES (?, ?, ?, ?)
ON CONFLICT(year) DO UPDATE SET
    generated_at  = excluded.generated_at,
    snapshot_json = excluded.snapshot_json,
    pdf           = excluded.pdf
`

type UpsertReconciliationSnapshotParams struct {
	Year         int64
	GeneratedAt  string
	SnapshotJson string
	Pdf          []byte
}

func (q *Queries) UpsertReconciliationSnapshot(ctx context.Context, arg UpsertReconciliationSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertReconciliationSnapshot,
		arg.Year,
		arg.GeneratedAt,
		arg.SnapshotJson,
		arg.Pdf,
	)
	return err
}
