// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteConcession = `-- name: DeleteConcession :exec
DELETE FROM concession WHERE year = ? AND group_code = ?
`

type DeleteConcessionParams struct {
	Year      int64
	GroupCode string
}

func (q *Queries) DeleteConcession(ctx context.Context, arg DeleteConcessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteConcession, arg.Year, arg.GroupCode)
	return err
}

const deleteConcessionForecastsByGroup = `-- name: DeleteConcessionForecastsByGroup :exec
DELETE FROM concession_forecast WHERE year = ? AND group_code = ?
`

type DeleteConcessionForecastsByGroupParams struct {
	Year      int64
	GroupCode string
}

func (q *Queries) DeleteConcessionForecastsByGroup(ctx context.Context, arg DeleteConcessionForecastsByGroupParams) error {
	_, err := q.db.ExecContext(ctx, deleteConcessionForecastsByGroup, arg.Year, arg.GroupCode)
	return err
}

const deleteConcessionForecastsByYear = `-- name: DeleteConcessionForecastsByYear :exec
DELETE FROM concession_forecast WHERE year = ?
`

func (q *Queries) DeleteConcessionForecastsByYear(ctx context.Context, year int64) error {
	_, err := q.db.ExecContext(ctx, deleteConcessionForecastsByYear, year)
	return err
}

const deleteConcessionsByYear = `-- name: DeleteConcessionsByYear :exec
DELETE FROM concession WHERE year = ?
`

func (q *Queries) DeleteConcessionsByYear(ctx context.Context, year int64) error {
	_, err := q.db.ExecContext(ctx, deleteConcessionsByYear, year)
	return err
}

const deleteForecastInvoicesByInvoice = `-- name: DeleteForecastInvoicesByInvoice :exec
DELETE FROM forecast_invoice WHERE invoice_id = ?
`

func (q *Queries) DeleteForecastInvoicesByInvoice(ctx context.Context, invoiceID int64) error {
	_, err := q.db.ExecContext(ctx, deleteForecastInvoicesByInvoice, invoiceID)
	return err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoice WHERE id = ?
`

func (q *Queries) DeleteInvoice(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteInvoice, id)
	return err
}

const deleteInvoicesByYear = `-- name: DeleteInvoicesByYear :exec
DELETE FROM invoice WHERE year = ?
`

func (q *Queries) DeleteInvoicesByYear(ctx context.Context, year int64) error {
	_, err := q.db.ExecContext(ctx, deleteInvoicesByYear, year)
	return err
}

const deletePaymentsByInvoice = `-- name: DeletePaymentsByInvoice :exec
DELETE FROM invoice_payment WHERE invoice_id = ?
`

func (q *Queries) DeletePaymentsByInvoice(ctx context.Context, invoiceID int64) error {
	_, err := q.db.ExecContext(ctx, deletePaymentsByInvoice, invoiceID)
	return err
}

const insertConcessionForecast = `-- name: InsertConcessionForecast :exec
INSERT INTO concession_forecast (year, forecast_id, group_code) VALUES (?, ?, ?)
`

type InsertConcessionForecastParams struct {
	Year       int64
	ForecastID string
	GroupCode  string
}

func (q *Queries) InsertConcessionForecast(ctx context.Context, arg InsertConcessionForecastParams) error {
	_, err := q.db.ExecContext(ctx, insertConcessionForecast, arg.Year, arg.ForecastID, arg.GroupCode)
	return err
}

const insertForecastInvoice = `-- name: InsertForecastInvoice :exec
INSERT INTO forecast_invoice (forecast_id, invoice_id, amount) VALUES (?, ?, ?)
`

type InsertForecastInvoiceParams struct {
	ForecastID string
	InvoiceID  int64
	Amount     string
}

func (q *Queries) InsertForecastInvoice(ctx context.Context, arg InsertForecastInvoiceParams) error {
	_, err := q.db.ExecContext(ctx, insertForecastInvoice, arg.ForecastID, arg.InvoiceID, arg.Amount)
	return err
}

const insertInvoice = `-- name: InsertInvoice :one
INSERT INTO invoice (year, issuer, nif, number, issue_date, net_amount, file_path, notes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertInvoiceParams struct {
	Year      int64
	Issuer    string
	Nif       string
	Number    string
	IssueDate string
	NetAmount string
	FilePath  sql.NullString
	Notes     sql.NullString
}

func (q *Queries) InsertInvoice(ctx context.Context, arg InsertInvoiceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertInvoice,
		arg.Year,
		arg.Issuer,
		arg.Nif,
		arg.Number,
		arg.IssueDate,
		arg.NetAmount,
		arg.FilePath,
		arg.Notes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertInvoicePayment = `-- name: InsertInvoicePayment :exec
INSERT INTO invoice_payment (invoice_id, paid_on, amount) VALUES (?, ?, ?)
`

type InsertInvoicePaymentParams struct {
	InvoiceID int64
	PaidOn    string
	Amount    string
}

func (q *Queries) InsertInvoicePayment(ctx context.Context, arg InsertInvoicePaymentParams) error {
	_, err := q.db.ExecContext(ctx, insertInvoicePayment, arg.InvoiceID, arg.PaidOn, arg.Amount)
	return err
}

const listConcessionForecastsByYear = `-- name: ListConcessionForecastsByYear :many
SELECT year, forecast_id, group_code FROM concession_forecast
WHERE year = ? ORDER BY group_code, forecast_id
`

func (q *Queries) ListConcessionForecastsByYear(ctx context.Context, year int64) ([]ConcessionForecast, error) {
	rows, err := q.db.QueryContext(ctx, listConcessionForecastsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConcessionForecast{}
	for rows.Next() {
		var i ConcessionForecast
		if err := rows.Scan(&i.Year, &i.ForecastID, &i.GroupCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConcessionsByYear = `-- name: ListConcessionsByYear :many
SELECT year, group_code, subtype_code, concept, requested_total, granted_amount
FROM concession WHERE year = ? ORDER BY group_code
`

func (q *Queries) ListConcessionsByYear(ctx context.Context, year int64) ([]Concession, error) {
	rows, err := q.db.QueryContext(ctx, listConcessionsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Concession{}
	for rows.Next() {
		var i Concession
		if err := rows.Scan(
			&i.Year,
			&i.GroupCode,
			&i.SubtypeCode,
			&i.Concept,
			&i.RequestedTotal,
			&i.GrantedAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForecastInvoicesByYear = `-- name: ListForecastInvoicesByYear :many
SELECT fi.forecast_id, fi.invoice_id, fi.amount FROM forecast_invoice fi
JOIN invoice i ON i.id = fi.invoice_id WHERE i.year = ? ORDER BY fi.invoice_id, fi.forecast_id
`

func (q *Queries) ListForecastInvoicesByYear(ctx context.Context, year int64) ([]ForecastInvoice, error) {
	rows, err := q.db.QueryContext(ctx, listForecastInvoicesByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ForecastInvoice{}
	for rows.Next() {
		var i ForecastInvoice
		if err := rows.Scan(&i.ForecastID, &i.InvoiceID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicePaymentsByYear = `-- name: ListInvoicePaymentsByYear :many
SELECT p.id, p.invoice_id, p.paid_on, p.amount FROM invoice_payment p
JOIN invoice i ON i.id = p.invoice_id WHERE i.year = ? ORDER BY p.invoice_id, p.id
`

func (q *Queries) ListInvoicePaymentsByYear(ctx context.Context, year int64) ([]InvoicePayment, error) {
	rows, err := q.db.QueryContext(ctx, listInvoicePaymentsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoicePayment{}
	for rows.Next() {
		var i InvoicePayment
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.PaidOn,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByYear = `-- name: ListInvoicesByYear :many
SELECT id, year, issuer, nif, number, issue_date, net_amount, file_path, notes
FROM invoice WHERE year = ? ORDER BY id
`

func (q *Queries) ListInvoicesByYear(ctx context.Context, year int64) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoicesByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Issuer,
			&i.Nif,
			&i.Number,
			&i.IssueDate,
			&i.NetAmount,
			&i.FilePath,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoice = `-- name: UpdateInvoice :exec
UPDATE invoice SET year=?, issuer=?, nif=?, number=?, issue_date=?, net_amount=?, file_path=?, notes=?
WHERE id=?
`

type UpdateInvoiceParams struct {
	Year      int64
	Issuer    string
	Nif       string
	Number    string
	IssueDate string
	NetAmount string
	FilePath  sql.NullString
	Notes     sql.NullString
	ID        int64
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) error {
	_, err := q.db.ExecContext(ctx, updateInvoice,
		arg.Year,
		arg.Issuer,
		arg.Nif,
		arg.Number,
		arg.IssueDate,
		arg.NetAmount,
		arg.FilePath,
		arg.Notes,
		arg.ID,
	)
	return err
}

const upsertConcession = `-- name: UpsertConcession :exec
INSERT INTO concession (year, group_code, subtype_code, concept, requested_total, granted_amount)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(year, group_code) DO UPDATE SET
    subtype_code=excluded.subtype_code, concept=excluded.concept,
    requested_total=excluded.requested_total, granted_amount=excluded.granted_amount
`

type UpsertConcessionParams struct {
	Year           int64
	GroupCode      string
	SubtypeCode    string
	Concept        string
	RequestedTotal string
	GrantedAmount  string
}

func (q *Queries) UpsertConcession(ctx context.Context, arg UpsertConcessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertConcession,
		arg.Year,
		arg.GroupCode,
		arg.SubtypeCode,
		arg.Concept,
		arg.RequestedTotal,
		arg.GrantedAmount,
	)
	return err
}
