// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getLatestReportByYear = `-- name: GetLatestReportByYear :one
SELECT id, year, generated_at, snapshot_json, pdf, superseded_at
FROM report
WHERE year = ? AND superseded_at IS NULL
ORDER BY generated_at DESC
LIMIT 1
`

func (q *Queries) GetLatestReportByYear(ctx context.Context, year int64) (Report, error) {
	row := q.db.QueryRowContext(ctx, getLatestReportByYear, year)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.GeneratedAt,
		&i.SnapshotJson,
		&i.Pdf,
		&i.SupersededAt,
	)
	return i, err
}

const insertReport = `-- name: InsertReport :one
INSERT INTO report (year, generated_at, snapshot_json, pdf, superseded_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type InsertReportParams struct {
	Year         int64
	GeneratedAt  string
	SnapshotJson string
	Pdf          []byte
	SupersededAt sql.NullString
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertReport,
		arg.Year,
		arg.GeneratedAt,
		arg.SnapshotJson,
		arg.Pdf,
		arg.SupersededAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markReportSuperseded = `-- name: MarkReportSuperseded :exec
UPDATE report SET superseded_at = ? WHERE id = ?
`

type MarkReportSupersededParams struct {
	SupersededAt sql.NullString
	ID           int64
}

func (q *Queries) MarkReportSuperseded(ctx context.Context, arg MarkReportSupersededParams) error {
	_, err := q.db.ExecContext(ctx, markReportSuperseded, arg.SupersededAt, arg.ID)
	return err
}
