// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: section.sql

package sqlc

import (
	"context"
)

const addPartnerSection = `-- name: AddPartnerSection :exec
INSERT INTO partner_section (partner_id, section_code) VALUES (?, ?)
ON CONFLICT(partner_id, section_code) DO NOTHING
`

type AddPartnerSectionParams struct {
	PartnerID   int64
	SectionCode string
}

func (q *Queries) AddPartnerSection(ctx context.Context, arg AddPartnerSectionParams) error {
	_, err := q.db.ExecContext(ctx, addPartnerSection, arg.PartnerID, arg.SectionCode)
	return err
}

const listPartnerSectionsByPartner = `-- name: ListPartnerSectionsByPartner :many
SELECT partner_id, section_code FROM partner_section WHERE partner_id = ? ORDER BY section_code
`

func (q *Queries) ListPartnerSectionsByPartner(ctx context.Context, partnerID int64) ([]PartnerSection, error) {
	rows, err := q.db.QueryContext(ctx, listPartnerSectionsByPartner, partnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PartnerSection{}
	for rows.Next() {
		var i PartnerSection
		if err := rows.Scan(&i.PartnerID, &i.SectionCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSections = `-- name: ListSections :many
SELECT code, label, active, display_order FROM section ORDER BY display_order, code
`

func (q *Queries) ListSections(ctx context.Context) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, listSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Section{}
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.Code,
			&i.Label,
			&i.Active,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSection = `-- name: UpsertSection :exec
INSERT INTO section (code, label, active, display_order)
VALUES (?, ?, ?, ?)
ON CONFLICT(code) DO UPDATE SET
  label=excluded.label, active=excluded.active, display_order=excluded.display_order
`

type UpsertSectionParams struct {
	Code         string
	Label        string
	Active       int64
	DisplayOrder int64
}

func (q *Queries) UpsertSection(ctx context.Context, arg UpsertSectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSection,
		arg.Code,
		arg.Label,
		arg.Active,
		arg.DisplayOrder,
	)
	return err
}
