// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlc

import (
	"context"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM session WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const getSession = `-- name: GetSession :one
SELECT token, partner_id, email, created_at, expires_at
FROM session WHERE token = ?
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.PartnerID,
		&i.Email,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO session (token, partner_id, email, created_at, expires_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	Token     string
	PartnerID int64
	Email     string
	CreatedAt string
	ExpiresAt string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.Token,
		arg.PartnerID,
		arg.Email,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
