// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: taxonomy.sql

package sqlc

import (
	"context"
)

const listExpenseSubtypes = `-- name: ListExpenseSubtypes :many
SELECT year, code, label, type_code FROM expense_subtype WHERE year = ? ORDER BY code
`

func (q *Queries) ListExpenseSubtypes(ctx context.Context, year int64) ([]ExpenseSubtype, error) {
	rows, err := q.db.QueryContext(ctx, listExpenseSubtypes, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseSubtype{}
	for rows.Next() {
		var i ExpenseSubtype
		if err := rows.Scan(
			&i.Year,
			&i.Code,
			&i.Label,
			&i.TypeCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseTypes = `-- name: ListExpenseTypes :many
SELECT year, code, label, category FROM expense_type WHERE year = ? ORDER BY code
`

func (q *Queries) ListExpenseTypes(ctx context.Context, year int64) ([]ExpenseType, error) {
	rows, err := q.db.QueryContext(ctx, listExpenseTypes, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseType{}
	for rows.Next() {
		var i ExpenseType
		if err := rows.Scan(
			&i.Year,
			&i.Code,
			&i.Label,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExpenseSubtype = `-- name: UpsertExpenseSubtype :exec
INSERT INTO expense_subtype (year, code, label, type_code)
VALUES (?, ?, ?, ?)
ON CONFLICT(year, code) DO UPDATE SET label=excluded.label, type_code=excluded.type_code
`

type UpsertExpenseSubtypeParams struct {
	Year     int64
	Code     string
	Label    string
	TypeCode string
}

func (q *Queries) UpsertExpenseSubtype(ctx context.Context, arg UpsertExpenseSubtypeParams) error {
	_, err := q.db.ExecContext(ctx, upsertExpenseSubtype,
		arg.Year,
		arg.Code,
		arg.Label,
		arg.TypeCode,
	)
	return err
}

const upsertExpenseType = `-- name: UpsertExpenseType :exec
INSERT INTO expense_type (year, code, label, category)
VALUES (?, ?, ?, ?)
ON CONFLICT(year, code) DO UPDATE SET label=excluded.label, category=excluded.category
`

type UpsertExpenseTypeParams struct {
	Year     int64
	Code     string
	Label    string
	Category string
}

func (q *Queries) UpsertExpenseType(ctx context.Context, arg UpsertExpenseTypeParams) error {
	_, err := q.db.ExecContext(ctx, upsertExpenseType,
		arg.Year,
		arg.Code,
		arg.Label,
		arg.Category,
	)
	return err
}
