// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: window.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getSubmissionWindow = `-- name: GetSubmissionWindow :one
SELECT year, state, opened_at, closed_at, deadline, current_expense_limit, investment_expense_limit
FROM submission_window WHERE year = ?
`

func (q *Queries) GetSubmissionWindow(ctx context.Context, year int64) (SubmissionWindow, error) {
	row := q.db.QueryRowContext(ctx, getSubmissionWindow, year)
	var i SubmissionWindow
	err := row.Scan(
		&i.Year,
		&i.State,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.Deadline,
		&i.CurrentExpenseLimit,
		&i.InvestmentExpenseLimit,
	)
	return i, err
}

const listSubmissionWindows = `-- name: ListSubmissionWindows :many
SELECT year, state, opened_at, closed_at, deadline, current_expense_limit, investment_expense_limit
FROM submission_window ORDER BY year DESC
`

func (q *Queries) ListSubmissionWindows(ctx context.Context) ([]SubmissionWindow, error) {
	rows, err := q.db.QueryContext(ctx, listSubmissionWindows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubmissionWindow{}
	for rows.Next() {
		var i SubmissionWindow
		if err := rows.Scan(
			&i.Year,
			&i.State,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.Deadline,
			&i.CurrentExpenseLimit,
			&i.InvestmentExpenseLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubmissionWindow = `-- name: UpsertSubmissionWindow :exec
INSERT INTO submission_window (year, state, opened_at, closed_at, deadline, current_expense_limit, investment_expense_limit)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(year) DO UPDATE SET
  state=excluded.state, opened_at=excluded.opened_at, closed_at=excluded.closed_at,
  deadline=excluded.deadline, current_expense_limit=excluded.current_expense_limit,
  investment_expense_limit=excluded.investment_expense_limit
`

type UpsertSubmissionWindowParams struct {
	Year                   int64
	State                  string
	OpenedAt               sql.NullString
	ClosedAt               sql.NullString
	Deadline               string
	CurrentExpenseLimit    string
	InvestmentExpenseLimit string
}

func (q *Queries) UpsertSubmissionWindow(ctx context.Context, arg UpsertSubmissionWindowParams) error {
	_, err := q.db.ExecContext(ctx, upsertSubmissionWindow,
		arg.Year,
		arg.State,
		arg.OpenedAt,
		arg.ClosedAt,
		arg.Deadline,
		arg.CurrentExpenseLimit,
		arg.InvestmentExpenseLimit,
	)
	return err
}
